local_working_path_base: /var/tmp/chef
repo_url: https://github.com/tjinjin/try-stretcher
branch: master
exclude_dirs:
  - tmp
environment: development
tarball_name: chef.tgz
deploy_to: /var/tmp/chef
deploy_roles:
  - web
  - bastion
stretcher_path: s3://tjinjin-server-stretcher/assets
manifest_path: s3://tjinjin-server-stretcher/manifests
stretcher_hook: stretcher.yml.erb
consul_host: deploy-test.tjinjin.net
